{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.Values.serviceName}}-ingress
  annotations: 
    {{range $key, $value := .Values.ingress.annotations}}
      {{ $key }}: {{ $value | quote }}
    {{end}}
spec:
  rules:
  - host: {{.Values.ingress.host}}
    http:
      paths:
      - path: {{.Values.ingress.path | quote}}
        backend:
          serviceName: {{.Values.serviceName}}
          servicePort: {{.Values.containerPort}}
  tls:
  - hosts:
    - {{.Values.ingress.host}}
    secretName: {{ printf "%s-ingress-letsencrypt" (.Values.ingress.host) }}
{{- end }}
