apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.serviceName}}-secret
data:
  AMQP_CONNECTIONSTRING: {{.Values.env.AMQP_CONNECTIONSTRING | b64enc | quote }}
  POSTGRES_CONNECTIONSTRING: {{.Values.env.POSTGRES_CONNECTIONSTRING | b64enc | quote }}
  REDIS_CONNECTIONSTRING: {{.Values.env.REDIS_CONNECTIONSTRING | b64enc | quote }}
