apiVersion: v1
kind: Service
metadata:
  name: { { .Values.serviceName } }
spec:
  ports:
    - port: { { .Values.containerPort } }
      protocol: TCP
  selector:
    app: { { .Values.serviceName } }
  type: ClusterIP
